# Data Management

Gaining value from data requires intention, planning, coordination and commitment. Both management and leadership are needed to treat data as a vital enterprise asset. [@dmbok]

*Data Management* is the development, execution, and supervision of plans, policies, programs, and practices that deliver, control, protect, and enhance the value of data and information assets through their life-cycles. [@dmbok]

*Data Management Professional* is any person who works in any facet of data management to meet strategic organizational goals. [@dmbok]

Data management activities are wide-ranging, including the ability to make consistent decisions about how to get strategic value from data to the technical deployment and performance of databases. Both technical and non-technical skills are needed. [@dmbok]

### Business Drivers

A key to competitive advantage is information/knowledge. Organizations that have reliable, high quality data about their customers, products, services, and operations can make better decisions than those without data or with unreliable data. Failure to manage data is similar to failure to manage capital. It results in waste and lost opportunity. The primary driver for data management is to enable organizations to get value from their data assets, just as effective management of financial and physical assets enables organizations to get value from those assets. [@dmbok]

### Goals

Within an organization, data management goals include:

 * Understanding and supporting the information needs of the enterprise and its stakeholders, including customers, employees, and business partners. 
 * Capturing, storing, protecting, and ensuring the integrity of data assets.
 * Ensuring the quality of data and information.
 * Ensuring the privacy and confident of stakeholder data.
 * Preventing unauthorized or inappropriate access, manipulation, or use of data and information.
 * Ensuring data can be used effectively to add value to the enterprise. [@dmbok]

## Essential Concepts

*Data* two definitions:

  * Represents facts about the world.
  * Information that has been stored digitally. 

Data is a means of representation. We need context for data to be meaningful. Context is data's representational system, one that includes a common vocabulary and set of relationships between components. [@dmbok]

Industry-level data standards can bring more consistency to data. [@dmbok]


### Data and Information

Data is called the raw material of information. Information is data in context. [@dmbok]

**Information - Data**

 * Sales report for last quarter - Data from data warehouse
 * Quarter over quarter performance measures - Quarter's results
 
*Central tenet of data management*: Data and information need to be managed, both will be of higher quality if they are managed together with uses and customer requirements in mind. [@dmbok]

### Data as an Organizational Asset

An asset is an economic resource, that can be owned or controlled, and that holds or produces value. [@dmbok]

Today's organizations rely on their data assets to make more effective decisions and to operate more efficiently. [@dmbok]

Being data-driven includes the recognition that data must be managed efficiently and with professional discipline, through a partnership of business leadership and technical expertise. [@dmbok]

### Data Management Principles

Data management shares characteristics with other forms of asset management. It involves knowing what data an organization has and what might be accomplished with it, then determining how best to use data assets to reach organizational goals. [@dmbok]

 * **Data is an asset with unique properties**: Unlike other assets, data is not consumed when it is used.
 * **The value of data can and should be expressed in economic terms**: Organizations need to develop consistent ways to quantify value of data. Both the costs and low quality data and the benefits of high quality data should be measured as well.
 * **Managing data means managing the quality of data**: Important to understand stakeholders requirements for quality and measure against these requirements.
 * **It takes Metadata to manage data**: The data used to manage and use data is *Metadata*.
 * **It takes planning to manage data**: To coordinate work and keep the end results aligned requires planning from an architectural and process perspective.
 * **Data management is cross-functional; it requires a range of skills and expertise**: A single team cannot manage all of an organization's data. 
 * **Data management requires an enterprise perspective**: Data management has local application, but it must be applied across the enterprise to be as effective as possible. 
 * **Data management must account for a range of perspectives**: Data management must constantly evolve to keep up with the ways data is created and used and the data consumers who use it. 
 * **Data management is life-cycle management**: Data has a life-cycle and managing data requires managing its life-cycle. 
 * **Different types of data have different life-cycle characteristics**: Data management practices have to be flexible enough to meet different kinds of data life-cycle requirements.
 * **Managing data includes managing the risks associated with data**: Data can be lost, stolen, or misused. Organizations need to consider the ethical implications of their uses of data.
 * **Data management requirements must drive Information Technology decisions**: Managing data requires an approach that ensures technology serves, rather than drives, an organization's strategic data needs. 
 * **Effective data management requires leadership commitment**: Data management involves a complex set of processes that, to be effective, require coordination, collaboration, and commitment. Getting there requires not only management skills, but also the vision and purpose that comes from committed leadership. [@dmbok]
 
### Data Management Challenges
 
#### Data Differs from Other Assets:

Physical assets can be pointed to, touched, and moved around. They can be in only one place at a time, Financial assets must be accounted for on a balance sheet. Data is different, its not tangible. It's difficult to put a monetary value on data, but without it, its difficult to measure how data contributes to organizational success. Despite the challenges with measuring the value of data, most people recognize that data has value. [@dmbok]

#### Data Valuation:

*Value* is the difference between the cost of a thing and the benefit derived from that thing. For data, this calculation is more complicated, because neither the costs nor the benefits of data are standardized. A primary challenge to data asset valuation is that the value of data is contextual. In relation to data management, establishing ways to associate ways to associate financial value with data is critical, since organizations need to understand assets in financial terms in order to make consistent decisions. Putting value on data becomes the basis of putting value on data management activities. Asking data management professionals and the stakeholders they support to understand the financial meaning of their work can help an organization transform its understanding of its own data and, through that, its approach to data management. Things to consider for valuing data: 

  * Cost of obtaining and storing data.
  * Cost of replacing data if it were lost.
  * Impact to the organization if data were missing.
  * Cost of risk mitigation and potential cost of risk associated with data.
  * Cost of improving data.
  * Benefits of higher quality data.
  * What competitors would pay for data.
  * What the data could be sold for.
  * Expected revenue from innovative uses of data. [@dmbok]

#### Data Quality:
Ensuring data is of high quality is central to data management. Organizations manage their data because they want to use it. If they cannot rely on it to meet business needs, then the effort to collect, store, secure, and enable access to it is wasted. to ensure data meets business needs, they must work with data consumers to define these needs, including characteristics that make data high quality. [@dmbok] 

Managing data quality has historically been treated as an afterthought, but the people who want to use the data cannot afford to be dismissive of quality. [@dmbok]

As importantly, poor quality data is simply costly to any organization. Costs come from:

 * Scrap and rework
 * Work-arounds and hidden correction processes
 * Organizational inefficiencies or low productivity
 * Organizational conflict
 * Low job satisfaction
 * Customer dissatisfaction
 * Opportunity costs, including inability to innovate
 * Compliance costs or fines
 * Reputational costs [@dmbok]
 
The corresponding benefits of high quality data include:

 * Improved customer experience
 * Higher productivity
 * Reduced risk
 * Ability to act on opportunities
 * Increased revenue
 * Competitive advantage gained from insights on customers, products, processes, and opportunities. [@dmbok]
 
As these costs and benefits imply, managing Data Quality is not a one-time job. Producing high quality data requires planning commitment, and a mindset that builds quality into processes and systems. [@dmbok]
 
#### Planning for Better Data

Deriving value from data does not happen by accident. It requires planning in many forms. It starts with the recognition the organizations can control how they obtain and create data. If they view data as a product that they create, they will make better decisions about it throughout its life-cycle. [@dmbok] These decisions require systems thinking because they involve:

 * The ways data connects business processes that might otherwise be seen as separate.
 * The relationship between business processes and the technology that supports them.
 * The design and architecture of systems and the data they produce and store.
 * The ways data might be used to advance organizational strategy. [@dmbok]
 
#### Metadata and Data Management
 
Metadata describes the data an organization has, what it represents, how it is classified, where it came from, how it moves within the organization, how it evolves through use, who can and cannot use it, and whether it is of high quality. [@dmbok]

The challenge is that metadata is a form of data and needs to be managed as such. Metadata management often provides a starting point for improvements in data management overall. [@dmbok]

#### Data Management is Cross-functional

Data is managed in different places within an organization by teams that have responsibility for different phases of the data life-cycle. Data management requires design skills to plan for systems, highly technical skills to administer hardware and build software, data analysis skills to understand issues and problems, analytic skills to interpret data, language skills to bring consensus to definition and models, as well as strategic thinking to see opportunities to serve customers and meet goals. [@dmbok]

#### Establishing an Enterprise Perspective

Managing data requires understanding the scope and range of data within an organization. Data originates in multiple places within an organization. [@dmbok]

Different departments may have different ways of representing the same concept. A goal of managing data as to make it fit together in common sense ways so that it is usable by a wide range of data consumers. [@dmbok]

#### Accounting for Other Perspectives

Knowledge of the potential uses of data enables better planning for the data life-cycle and, with that, for better quality data. [@dmbok]

#### The Data Life-Cycle

Like other assets data has a life-cycle. Well-managed data is managed strategically, with a vision of how the organization will use its data. A strategic organization will define not only its data content requirements, but also its data management requirements. These include policies and expectations for use, quality, controls, and security; an enterprise approach to architecture and design; and a sustainable approach to both infrastructure and software development. [@dmbok]

The data life-cycle includes processes that create or obtain data, those that move, transform, and store it and enable it to be maintained and shared, and those that use or enhanced, or aggregated. As data is used or enhanced, new data is often created, so the life-cycle has internal iterations that are not shown on the diagram, Data is rarely static. Managing data involves a set of interconnected processes aligned with the data life-cycle. [@dmbok]

The focus of data management on the data life-cycle has several important implications:

 * Creation and usage are the most critical points in the data life-cycles.
 * Data Quality must be managed throughout the data life-cycle.
 * Metadata Quality must be managed through the data life-cycle. 
 * Data Security must be managed throughout the data life-cycle.
 * Data Management efforts should focus on the most critical data. [@dmbok]
 
#### Different Types of Data

Managing data is made more complicated by the fact that there are different types of data that have different life-cycle management requirements. Data can be classified by type of data or by content or by format or by the level of protection the data requires. Data can also be classified by how and where it is stored or accessed. [@dmbok]

#### Data and Risk

Data represents risk:

 * Low quality data leads to bad information.
 * Data can be misunderstood and misused.
 
#### Data Management and Technology

#### Effective Data Management Requires Leadership and Commitment

### Data Management Strategy

## Data Management Frameworks

### Strategic Alignment Model

### The Amsterdam Information Model

### The DAMA-DMBOK Framework

### DMBOK Pyramid

### DAMA Data Management Framework Evolved

## DAMA and the DMBOK
