# Data Governance

*Data Governance* is defined as the exercise of authority and control over the  management of data assets. [@dmbok]

Those that establish a formal Data Governance program exercise authority and control with greater intentionally. Such organizations are better able to increase the value they get from their data assets. [@dmbok]

The Data Governance function guides all other data management functions. The purpose of Data Governance is to ensure that data is managed properly, according to policies and best practices. [@dmbok]

Most programs include:

 * Strategy
 * Policy
 * Standards and quality
 * Oversight
 * Compliance
 * Issue management
 * Data management projects
 * Data asset valuation
 
For most organizations, adopting formal Data Governance requires the support of organizational change management, as well as sponsorship from a C-level executive, such as Chief Risk Officer, Chief Financial Officer, or Chief Data Officer. [@dmbok]
 
Organizations becoming data-driven often face cultural challenges. Cultural challenges can derail any strategy. Data Governance efforts need to include a cultural change component, supported by strong leadership. [@dmbok]

To Benefit from data as a corporate asset, the organizational culture must learn to value data and data management activities. Even with the best data strategy, data governance and data management plans will not succeed unless the organization accepts and manages change. [@dmbok]

### Business Drivers

Data governance is not an end in itself. It needs to align directly with organizational strategy. The more clearly it helps solve organizational problems, the more likely people will change behaviors and adopt governance practices. Drivers for data governance most often focus on reducing risks or improving processes. [@dmbok]

 * Reducing Risk
   + General risk management
   + Data security
   + Privacy
 * Improving Processes
   + Regulatory compliance
   + Data quality improvement
   + Metadata Management
   + Efficiency in development projects
   + Vendor management
  
It is important to clarify the particular business drivers for data governance within an organization and to align them with overall business strategy. [@dmbok]

Data governance is not a one-time thing. Governing data requires an ongoing program focused on ensuring that an organization gets value from its data and reduces risks related to data.. A Data Governance team can be a virtual organization or a line organization with specific accountabilities. To be effective, the roles and activities within data governance need to be well understood. They should be built around an operating framework that functions well in the organization. A data governance program should take into account distinctive organizational and cultural issues and the specific data management challenges and opportunities within the organization. [@dmbok]

### Goals and Principles

The goal of Data Governance is to enable an organization to manage data as an asset. To achieve this overall goal a DG program must be sustainable, embedded, and measured. [@dmbok]

The following principles can help set a strong foundation for data governance:

 * **Leadership and strategy**: Successful Data Governance starts with visionary and committed leadership. Data management activities are guided by a data strategy that is itself driven by the enterprise business strategy.
 * **Business-driven**: Data Governance is a business program, and, as such, must govern IT decisions related to data as much as it governs business interaction with data.
 * **Shared responsibility**: Across all Data Management Knowledge Areas, data governance is a shared responsibility between business data stewards and technical data management professionals.
 * **Multi-layered**: Data Governance occurs at both the enterprise and local levels and often at levels in between.
 * **Framework-based**: Because data governance activities require coordination across functional areas, the DG program must establish an operating framework that defines accountabilities and interactions.
 * **Principle-based**: Guiding principles are the foundation of DG activities, and especially of DG policy. Often, organizations develop policy without formal principles - they are trying to solve particular problems. Principles can sometimes be reverse-engineered from policy. However, it is best to articulate a core set of principles and best practices as part of policy work. Reference to principles can mitigate potential resistance. Additional guiding principles will emerge over time within an organization. Publish them in a shared internal environment along with other data governance artifacts. 
 
### Essential Concepts

Data governance ensures data is properly managed without directly executing data management. Data governance represents an inherent separation of duty between oversight and execution. [@dmbok]

#### Data-centric Organization

A data-centric organization values data as an asset and manages data through all phases of its life-cycle, including project development and ongoing operations. Data is no longer treated as a by-product or process and applications. Ensuring data is of high quality is a goal of business processes. As organizations strive to make decisions based on insights gained from analytics, effective data management becomes a very high priority. [@dmbok]

To become data-centric, organizations need to think differently and recognize that managing data is different from managing IT. [@dmbok]

While each organization needs to evolve its own principles, those that seek to get more value from their data are likely to share the following:

 * Data should be managed as a corporate asset
 * Data management best practices should be incented across the organization
 * Enterprise data strategy must be directly aligned with overall business strategy
 * Data management processes should be continuously improved
 
#### Data Governance Organization

Data governance includes:

 * Legislation-like functions - defining policies, standards, and the Enterprise Data Architecture
 * Judicial-like functions - issue management and escalation
 * Executive functions - protecting and serving, administrative responsibilities
 
 Each organization should adopt a governance model that supports its business strategy and is likely to succeed within its own cultural context. [@dmbok]
 
 #### Data Governance Operating Model Types
 
 #### Data Stewardship
 
 *Data Stewardship* is the most common label to describe accountability and responsibility for data and processes that ensure effective control and use of data assets. [@dmbok]
 
Data stewardship activities will focus on some if not all, of the following:

 * Creating and managing core Metadata
 * Documenting rules and standards
 * Managing data quality issues
 * Executing operational data governance activities
 
#### Types of Data Stewards

Data Stewards manage data assets on behalf of others and in the best interests of the organization (McGilvray, 2008). Data Stewards represent the interests of all stakeholders and must take an enterprise perspective to ensure enterprise data is of high quality and can be used effectively. Effective Data Stewards are accountable and responsible for data governance activities and have a portion of their time dedicate to these activities. [@dmbok]

Formally appointed Data Stewards may by differentiated by their place within an organization, by the focus of their work, or by both. [@dmbok]

Types:

 * Chief Data Stewards
 * Executive Data Stewards
 * Enterprise Data Stewards
 * Business Data Stewards
 * A Data Owner
 * Technical Data Stewards
 * Coordinating Data Stewards
 
#### Data Policies

Data policies are directives that codify principles and management intent into fundamental rules governing the creation, acquisition, integrity, security, quality, and use of data and information. [@dmbok]

Data policies are global. They support data standards, as well as expected behavior related to key aspects of data management and use. Data policies describe the 'what' of data governance, while standards and procedures describe 'how' to do data governance. There should be relatively few data policies, and they should be stated briefly and directly. [@dmbok]

#### Data Asset Valuation

*Data asset valuation* is the process of understanding and calculating the economic value of data to an organization. [@dmbok]

The key to understanding the value of a non-fungible item is understanding how it is used and the value brought by its usage (Redman, 1996). How an organization gets value from customer data can be a competitive differentiator. [@dmbok]

Most phases of the data life-cycle involve costs. Data only brings value when it is used. So value comes when the economic benefit of using data outweighs the costs of acquiring and storing it, as well as managing risk related to usage. [@dmbok]

Some ways to measure value include:

 * Replacement cost
 * Market value
 * Identified opportunities
 * Selling data
 * Risk cost

## Activities

### Define Data Governance for the Organization

Data governance is most effective when it is an enterprise effort, rather that isolated to a particular functional area. [@dmbok]

### Perform Readiness Assessment

Typical assessments include:

 * Data management maturity
 * Capacity to change
 * Collaborative readiness
 * Business alignment
 
### Perform Discovery and Business Alignment

A DG program must contribute to the organization by identifying and delivering on specific benefits. Discovery can also identify opportunities for DG to improve the usefulness of data and content. Business alignment attaches business benefits to DG program elements. [@dmbok]

Data quality analysis is part of discover. [@dmbok]

Assessment of data management practices is another key aspect of the data governance discovery process. [@dmbok]

### Develop Organizational Touch Points

How DG will be perceived by the organization. [@dmbok]

### Develop Data Governance Strategy

Deliverable include:

 * Charter
 * Operating framework and accountabilities
 * Implementation roadmap
 * Plan for operational success
 
### Define the DG Operating Framework

Consider these areas when constructing an organization's operating model:

 * Value of data to the organization
 * Business model
 * Cultural factors
 * Impact of regulation

### Develop Goals, Principles, and Policies

Goals, principles, and policies are typically drafted by either by data management professionals, business policy staff, or a combination, under the auspices of data governance. Next, Data Stewards and management review and refine them. Then, the Data Governance Council conducts the final review, revision, and adoption. [@dmbok]

### Underwrite Data Management Projects

The key to promoting initiatives is to articulate the ways they improve efficiency and reduce risk. Organizations that want to get more value from their data to prioritize development of or improvement of data management capabilities. [@dmbok]

The DGC helps define the business case and oversees project status and progress on data management improvement projects. Data management projects may be considered part of the overall IT project portfolio. [@dmbok]

### Engage Change Management

Organizational Change Management is the vehicle for bringing about change in an organization's systems and processes. An organization that is mature in its management of change builds a clear organizational vision, actively leads and monitors change from the top, and designs and manages smaller change efforts. [@dmbok]

A change management program supporting formal Data Governance should focus communications on:

 * Promoting the value of data assets
 * Monitoring and acting on feedback about data governance activities
 * Implementing data management training
 * Measuring the effects of change management on in five key areas:
   + Awareness of the need to change
   + Desire to participate and support change
   + Knowledge about how to change
   + Ability to implement new skills and behaviors
   + Reinforcement to keep the change in place
 * Implementing new metrics and KPIs
 
### Engage in Issue Management

Issue management is the process for identifying, quantifying, prioritizing, and resolving data governance-related issues, including:

 * Authority
 * Change management escalations
 * Compliance
 * Conflicts
 * Conformance
 * Contracts
 * Data security and identity
 * Data quality
 
Data governance requires control mechanisms and procedures for:

 * Identifying, capturing, logging, tracking, and updating issues
 * Assignment and tracking of action items
 * Documenting stakeholder viewpoints and resolution alternatives
 * Determining, documenting, and communicating issue resolutions
 * Facilitating objectives, neutral discussions where all viewpoints are heard
 * Escalating issues to higher levels of authority
 
### Assess Regulatory Compliance Requirements

### Implement Data Governance

It is best to create an implementation roadmap that illustrates the timeframe for and relationship between different activities. [@dmbok]

Some DG work is foundational, prioritizing activities in the early stages include:

 * Defining data governance procedures required to meet high priority goals
 * Establishing a business glossary and documenting terminology and standards
 * Coordinating with Enterprise Architecture and Data Architecture to support better understanding of the data and the systems
 * Assigning financial value to data assets to enable better decision-making and to increase understanding of the role that data plays in organizational success
 
### Sponsor Data Standards and Procedures

Standards help define quality because they provide a means of comparison. They also offer the potential to simplify processes. [@dmbok]

Enforcing standards should promote consistent results from the processes using them. [@dmbok]

DG Standards should be mandatory. [@dmbok]

Data standards can take different forms depending on what they describe. The level of detail in data standards documentation depends, in part, on organizational culture. [@dmbok]

Data management procedures are the documented methods, techniques, and steps followed to accomplish specific activities that produce certain outcomes and supporting artifacts.  [@dmbok]

Examples of concepts that can be standardized within the Data Management Knowledge Areas include:

 * **Data Architecture**: Enterprise data models, tool standards, and system naming conventions
 * **Data Modeling and Design**: Data model management procedures, data modeling naming conventions, definition standards, standards domains, and standard abbreviations
 * **Data Storage and Operations**: Tool standards, standards for database recovery and business continuity, database performance, data retention, and external data acquisition
 * **Data Security**: Data access security standards, monitoring and audit procedures, storage security standards, and training requirements
 * **Data Integration**: Standards methods and tools used for data integration and interoperability
 * **Documents and Content**: Content management standards and procedures, including use of enterprise taxonomies, support for legal discovery, document and email retention periods, electronic signatures, and report distribution approaches
 * **References and Master Data**: Reference Data Management control procedures, systems of data record, assertions establishing and mandating use, standards for entity resolution
 * **Data Warehousing and Business Intelligence**: Tool standard, processing standards and procedures, report and visualization formatting standards, standard for Big Data Handling
 * **Metadata**: Standards business and technical Metadata to be captured, Metadata integration procedures and usage
 * **Data Quality**: Data quality rules, standard measurement methodologies, data remediation standards and procedures
 * **Big Data and Data Science**: Data source identification, authority, acquisition, system of record, sharing and refresh
 
### Develop a Business Glossary

Data Stewards ares generally responsible for business glossary content. Developing and documenting standard data definitions reduces ambiguity and improves communication. Definitions must be clear, rigorous in wording, and explain any exceptions, synonyms or variants. Approvers of terminology should include representatives from core user groups. [@dmbok]

Business glossaries have the following objectives:

 * Enable common understanding of the core business concepts and terminology
 * Reduce the risk that data will be misused due to inconsistent understanding of the business concepts
 * Improve the alignment between technology assets and the business organization
 * Maximize search capability and enable access to documented institutional knowledge
 
A business glossary is not merely a list of terms and definitions. Each term will also be associated with other valuable Metadata: synonyms, metrics, lineage, business rules, the steward responsible for the term, etc. [@dmbok]

### Sponsor Data Asset Valuation

Data and information are assets because the have or can create value. Today's accounting practices consider data an intangible asset, much like software, documentation, expert knowledge, trade secrets, and other intellectual property. That said, organizations find it challenging to put monetary value on data. The DGC should organize the effort and set standards for doing so. [@dmbok]

Estimate the value of business losses due to inadequate information. Information gaps - the difference between what information is needed and what is available - represents business liabilities. The cost of closing or preventing gaps can be used to estimate of business value of the missing data. From there, the organization can develop models to estimate the value of the information that does exist. [@dmbok]

Value estimates can be build into data strategy roadmap that will justify business cases for root cause solutions to quality issues, as well as for the other governance initiatives. [@dmbok]

### Embed Data Governance

In order to deepen the organization's understanding of data governance in general, its application locally, and to learn from each other, create a Data Governance Community of Interest. This is particularly useful in the first years of governance, and will likely taper off as the DG operations become mature. [@dmbok]

## Tools and Techniques

Data governance is fundamentally about organizational behavior. Before choosing a tool for a specific function, like a business glossary solution, an organization should define its overall governance goals and requirements with an eye to build out a tool set. [@dmbok]

### Online Presence / Websites

Data Governance program should have an online presence. It can make core document s available via a central website or a collaboration portal. A DG program website should include:

 * The Data Governance strategy and program charter, including vision, benefits, goals, principles, and implementation roadmap
 * Data policies and data standards
 * Descriptions of data stewardship roles and responsibilities
 * Program news announcements
 * Links to forums for a Data Governance Community of Interest
 * Links to executive messages regarding data governance topics
 * Reports on Data Quality measurements
 * Procedures for issue identification and escalation
 * Links to request services or capture issues
 * Documents, presentations, and training programs with links to related online resources
 * Data Governance program contact information
 
### Business Glossary

### Workflow Tools

### Document Management Tools

### Data Governance Scorecards

## Implementation Guidelines

Most roll-out strategies are incremental, either applying DG first to a large effort, such as MDM, or by a region or division. Rarely is DG deployed enterprise-wide as a first effort. [@dmbok]

### Organization and Culture

Effective and long-lasting data governance programs require a cultural shift in organizational thinking and behavior about data, as well as an ongoing program of change management to support the new thinking, behaviors, policies, and processes to achieve the desired future state of behavior around data. [@dmbok]

The target of organization change is sustainability. Sustainability is a quality of a process that measures how easy it is for the process to continue to add value. Sustaining a data governance program requires planning for change. [@dmbok]

### Adjustment and Communication

Tools required to manage and communicate changes:

 * Business / DG strategy map
 * DG roadmap
 * Ongoing business case for DG
 * DG metrics
 
## Metrics
 


